[package]
name = "taskwarrior-summary"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-to-tui = "7.0.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
strum = "0.26.3"
strum_macros = "0.26.4"
